# Generated by Django 4.2.27 on 2025-12-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('image', models.FileField(upload_to='category/image')),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('orange', 'Orange'), ('pink', 'Pink'), ('gray', 'Gray')], default='black', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
