# Generated by Django 4.2.27 on 2025-12-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('premium', 'Premium'), ('standard', 'Standard'), ('economy', 'Economy'), ('luxury', 'Luxury'), ('budget', 'Budget'), ('other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('xiaomi', 'Xiaomi'), ('huawei', 'Huawei'), ('lg', 'LG'), ('sony', 'Sony'), ('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('zara', 'Zara'), ('h&m', 'H&M'), ('other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('like_new', 'Like New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('damaged', 'Damaged'), ('for_parts', 'For Parts')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', '2XL'), ('xxxl', '3XL'), ('one_size', 'One Size'), ('other', 'Other')], max_length=100),
        ),
    ]
