# Generated by Django 4.2.27 on 2025-12-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_country_product_service_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='desc',
            new_name='description',
        ),
    ]
